language: java
jdk:
- oraclejdk9
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  app:
    master: api-shipcollision
    dev: dev-api-shipcollision
  api_key:
    master:
      secure: UOjZgs6XjE+XPfA1n7kVDfAHeprZv1DzZqyPkrvZ6Efw+dbeDC7HkUZDG3GTzNknN1Y7zkYM0mO++p7FYwLCSbcaYUVxJ64K8zEyOJvIp6/U8+3kmiPstgMjFxGM15i9dGbqfsXxdrI2xSI0FHR2U1Z6d0eMlIsIS37IRg3BT1jvBwMIytlBufHO08dY5fVhD+Oe777hmBPAllU4sbBD2Qe39u55/DMLhtMqpghOVgR7rjNIlPhdo300jXzmjk32P/JBCd5HYNysr9jw858c7ATkDLgAmRthML+wcMrATQGEsZvkh9nGSMAbsnihcEWrD07KmEy/LhoH/kT548mtziw8HzaYUhktgkwiLJluVTCN+Mhw2P7/M06WRkEEupDfy6Q3HFj8DD12DebzbyPb0n1+6T0w94X0Xu5b4cmcZIlxTDA9nM/AEEKigpFs4oNzVIzbrz9vjV35puS3w9PmBIon6Demwy6ithdK+u7BA1IpWuNh0DrTX2kIpAkq2geZnOZg4zbnO2sobedpXDc8Rms5ADvD5b2mYOThVkK7uM3NH4ZLSuezyJugiWetzP0YIU8ULSMgHBAnLB/FFaJZB+E7IU1I+xFB4PSnxPUquDfnjLBg4/R+5qz2+o/xlEXvxB+xYad8r0pWCaJ5BJC8ilDGAdp2DwclbNk79xcdiE0=
    dev:
      secure: mY39B35qO+6u1ihQjVVGMVxvjAGBmk3B2//xYraao/fddT0mwOtx61NdHOuLazAGxStxMhUTdyCfRnxc4HhXUvkCnBmtG7V5D6oftxV8POF37BZJ7t1Q2+Yvh+kTNEzxFbA0ykzk0spc9bfqfYVEjEO1E8SMHFU7TCCjYroR0KxskP32CuW4QOfT7roHiZYj1RVSLjEOQHaRlTd1RgoIkv1O1g1C/ScllBY4vUSfr6LdBO+iEFodfRBj/jkMM46zrOVQnNDa3msOH6fK5c/9T91Dxp8H6bVNm6kelyXB4jmfOwr/Gj2UlRg78eMLziKkSgFkeRNeffiOeBiEL9IDcJZ3ZmHWA7I9/maGpKo4YYKxHoy6sSjH5aabIMMe+vFw9Czu0QWxG+NbSFJ0dneMEjwnfUMi/rYqZUBfp10OkOm16cVON2XgtRCuxfwLcBl2V5M0nER30nGOB1U8oSKW4cr8KQuauFNIL+e2nspxGsr5ez41dXw8FdRFdTV7l/KqnB4pgrnqcRw59hEVDkGjoZxVntrOXTLfFVt3+GDvJCEWbpJiKvhZ4M8akyZLoc+eR3nAGrvOrC/XPSM6hFBD1qCCF4GXqYDHPfrhhTzZ6ADSvZ3PNiPHxYSasXOlH/TIJZu/tBMiYpKPpvKBep6M0A+3rTEbQBlxyyvF5yhOfdM=
